### ISSUE TITLE
Формирование окружения разработчика

### ISSUE THREAD

**Issue by alehinsasha** [needigeo/bddfinaltask#1]
- [x] Внешние отчеты и обработки разбираются на исходники
- [x] Структура каталогов репозитория из bootstrap

**Comment by needigeo** [comment]
Сделано.

**Comment by alehinsasha** [comment]
в \src должны быть исходники обработок проверки фич

**Comment by needigeo** [comment]
Над обработками еще работаю. Поместил для тестирования precomit в репозитарий vanessa-behavior

**Comment by alehinsasha** [comment]
Ок. Цепляйте мои issue в своих коммитах.
