### ISSUE TITLE
Формирование описания разработки

### ISSUE THREAD

**Issue by alehinsasha** [needigeo/bddfinaltask#2]
- [x] Коммиты с доступным описанием
- [x] Коммиты привязаны к issue

**Comment by needigeo** [comment]
Что подразумевается под 1 пунктом "Коммиты с доступным описанием"?

**Comment by needigeo** [comment]
Добавил коммит с привязкой к issue.

**Comment by alehinsasha** [comment]
> Что подразумевается под 1 пунктом "Коммиты с доступным описанием"?

У вас доступные описания коммитов.
